-- ====================================================================
-- SPARK SPRINT MANAGEMENT SYSTEM - DATABASE MIGRATION SCRIPT
-- Version: 1.0.0
-- Date: August 17, 2025
-- Purpose: Fix column data type issues and ensure schema compatibility
-- ====================================================================

-- Backup existing data (if needed)
CREATE TABLE SPARK_SPRINT_INFO_BACKUP AS SELECT * FROM SPARK_SPRINT_INFO;

-- Fix Status Column Issue
-- First, update any existing status values to proper format
UPDATE SPARK_SPRINT_INFO SET STATUS = 1 WHERE STATUS IS NULL;
COMMIT;

-- Add new columns with correct data types if they don't exist
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SPARK_SPRINT_INFO ADD STATUS_NEW NUMBER(10,0) DEFAULT 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- Ignore "name is already used" error
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SPARK_SPRINT_INFO ADD FROM_DATE_NEW TIMESTAMP(6) WITH TIME ZONE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SPARK_SPRINT_INFO ADD TO_DATE_NEW TIMESTAMP(6) WITH TIME ZONE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Copy data to new columns
UPDATE SPARK_SPRINT_INFO SET 
    STATUS_NEW = CASE 
        WHEN STATUS IS NULL THEN 1
        ELSE STATUS 
    END,
    FROM_DATE_NEW = FROM_DATE,
    TO_DATE_NEW = TO_DATE;

COMMIT;

-- Drop old columns and rename new ones
ALTER TABLE SPARK_SPRINT_INFO DROP COLUMN STATUS;
ALTER TABLE SPARK_SPRINT_INFO DROP COLUMN FROM_DATE;
ALTER TABLE SPARK_SPRINT_INFO DROP COLUMN TO_DATE;

ALTER TABLE SPARK_SPRINT_INFO RENAME COLUMN STATUS_NEW TO STATUS;
ALTER TABLE SPARK_SPRINT_INFO RENAME COLUMN FROM_DATE_NEW TO FROM_DATE;
ALTER TABLE SPARK_SPRINT_INFO RENAME COLUMN TO_DATE_NEW TO TO_DATE;

-- Add constraints and indexes for performance
ALTER TABLE SPARK_SPRINT_INFO ADD CONSTRAINT CHK_SPRINT_STATUS CHECK (STATUS IN (0, 1, 2, 3));
CREATE INDEX IDX_SPRINT_STATUS ON SPARK_SPRINT_INFO(STATUS);
CREATE INDEX IDX_SPRINT_DATES ON SPARK_SPRINT_INFO(FROM_DATE, TO_DATE);
CREATE INDEX IDX_SPRINT_TEAM ON SPARK_SPRINT_INFO(TRAM_ID);

-- Create sequence for auto-increment if not exists
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SPARK_SPRINT_INFO_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Ensure proper permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON SPARK_SPRINT_INFO TO SPARK;

COMMIT;

-- Verification queries
SELECT 'SPRINT_INFO_SCHEMA_CHECK' as CHECK_TYPE, COUNT(*) as RECORD_COUNT FROM SPARK_SPRINT_INFO;
SELECT 'STATUS_VALUES_CHECK' as CHECK_TYPE, STATUS, COUNT(*) as COUNT FROM SPARK_SPRINT_INFO GROUP BY STATUS;

-- Migration complete marker (removed SQL*Plus specific PRINT statement to stay JDBC/Flyway compatible)
